### ISSUE TITLE
build issue 

### ISSUE THREAD

**Issue by salahaldin** [gharia/spring-boot-angular#2]
$ gradlew build

FAILURE: Build failed with an exception.
- What went wrong:
  org.codehaus.groovy.runtime.DefaultGroovyMethods.each(Ljava/util/List;Lgroovy/lang/Closure;)Ljava/util/List;
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.952 secs

**Comment by gharia** [comment]
This has been fixed. Updated gradle wrapper. Please try pulling the latest code.

**Comment by salahaldin** [comment]
Thanks work like charm, I have noticed that your tables naming might be troubling with postgres since user is a keyword. Also there is a missing unique key in user_authority table. Other than that, excellent tutorial.
